### PR TITLE
Updates to dist.ini

### PR DESCRIPTION
**Pull request by paultcochrane**
A few things needed tidying up in the `dist.ini`.  The commit messages are hopefully self-explanatory and they are separated so that they can be cherry-picked should this be necessary.

### CODE REVIEW

**Comment by chiselwright** [comment]
I'm unable to merge this one; I'm stuck on my phone approving these tonight.

**Comment by paultcochrane** [comment]
No worries, I'll merge the code, fix the conflicts and re-submit the PR.

**Comment by paultcochrane** [comment]
Ok, this should be fixed up and ok to merge now.

**Comment by paultcochrane** [comment]
And many thanks for reacting to the PRs so quickly!

**Pull request merged**
